server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/OrderHostel